{ pkgs, ... }:
let
  author = "cybardev";
  pname = "anisette-server";
  version = "0.0.1";
in
pkgs.buildDubPackage {
  inherit pname;
  inherit version;

  src = pkgs.fetchFromGitHub {
    owner = author;
    repo = "anisette-v3-server";
    rev = "b23b3d4ecf028012f36f79100c465e678c41635d";
    hash = "sha256-h5Yh2WzJiqj1kRG2kI55iByuVXh81lbvHgX8++3zrEY=";
  };

  # generated by dub-to-nix
  dubLock = ./dub-lock.json;

  buildInputs = with pkgs; [
    clang
    ldc
    libz
    libressl
  ];

  installPhase = ''
    runHook preInstall
    install -Dm755 ${pname} -t $out/bin
    runHook postInstall
  '';
}
