name: "Push to Cachix"

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NIXPKGS_ALLOW_UNFREE: 1
      NIXPKGS_ALLOW_INSECURE: 1
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v16
      with:
        name: cybardev
        authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
    - run: nix build --impure
    - run: nix flake check
